version: "3.8"

networks:
  mynet:
    name: ${MY_NETWORK}
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports: 
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - ${MY_NETWORK}
    volumes:
      - ./requirements/wordpress/wordpress:/var/www/html
      
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./requirements/mariadb/data:/var/lib/mysql
    networks:
      - ${MY_NETWORK}

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
    depends_on:
      - mariadb
    volumes:
      - ./requirements/wordpress/wordpress:/var/www/html
    networks:
      - ${MY_NETWORK}
    

