version: "3.8"

networks:
  mynet:
    name: ${MY_NETWORK}
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - ${MY_NETWORK}
    volumes:
      - wordpress_page:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    environment:
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    expose:
      - "3306"
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - ${MY_NETWORK}
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
      ADMIN_USER_NAME: ${ADMIN_USER_NAME}
      ADMIN_USER_PASS: ${ADMIN_USER_PASS}
      AUTHOR_USER_NAME: ${AUTHOR_USER_NAME}
      AUTHOR_USER_PASS: ${AUTHOR_USER_PASS}
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb
    volumes:
      - wordpress_page:/var/www/html
    networks:
      - ${MY_NETWORK}
    restart: always

volumes:
  wordpress_page:
    driver: local
    driver_opts:
      type: none
      device: /home/yeonwkan/data/wordpress 
      o: bind
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      device: /home/yeonwkan/data/db
      o: bind
